### ISSUE TITLE
Crashes with new Transformers version

### ISSUE THREAD

**Issue by barakw2021** [Xirider/finetune-gpt2xl#13]
Here's the error:

Traceback (most recent call last):
  File "run_clm.py", line 478, in <module>
    main()
  File "run_clm.py", line 422, in main
    trainer = Trainer(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 295, in __init__
    logging.set_verbosity(log_level)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/utils/logging.py", line 161, in set_verbosity
    _get_library_root_logger().setLevel(verbosity)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 1409, in setLevel
    self.level = _checkLevel(level)
  File "/root/miniconda3/lib/python3.8/logging/__init__.py", line 194, in _checkLevel
    raise ValueError("Unknown level: %r" % level)

The fix was to install transformers v4.6.0 from pip

**Comment by Xirider** [comment]
Thanks for reporting! I pinned now the transformers dependency to 4.7.0.
